### ISSUE TITLE
First installation failed

### ISSUE THREAD

**Issue by faguirre154** [apprenda/bxcr#11]
Installation failed at first time and I am trying to reinstall it but I am facing this error: OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 10054. I ran vagrant init apprenda/windows2012r2 otherwise with vagrant up was not start.

**Comment by austinlparker** [comment]
Hi, could you try the following:

1. Run vagrant destroy to delete existing vms from the checkout directory
2. Run vagrant up again

If it fails again, could you post more of the log in a comment? Also, please include the OS version you are running.

**Comment by austinlparker** [comment]
Closing this issue as a new one was opened for the same problem.
