### ISSUE TITLE
Allow for kubectl connection to K8S cluster

### ISSUE THREAD

**Issue by mammerman** [apprenda/bxcr#8]
Use port forwarding in the vagrant config when creating a K8S cluster to forward `kubectl` commands issued against the host IP to the cluster.  This will allow for accessing the cluster from outside the host (like RDP is setup for the Windows node)

**Comment by austinlparker** [comment]
What ports need to be forwarded? Also, can you give `kubectl` an arbitrary port to connect to? I'd prefer if we set the host port to something higher so that in the event you're running a local cluster for some reason that you won't conflict.

**Comment by mammerman** [comment]
Default non-TLS port is 8080.  We can make it something arbitrary if we want although that default should be ok, a higher port number is important because on *nix machines, anything running as non-root cannot bind to ports < 1024.

https://kubernetes.io/docs/admin/accessing-the-api/
