### ISSUE TITLE
apprenda-linux provisioning fails

### ISSUE THREAD

**Issue by mammerman** [apprenda/bxcr#9]
Looks like the repo can't be mounted due to version # in path:
`==> apprenda-linux: Running provisioner: shell...`
`apprenda-linux: Running: /tmp/vagrant-shell20170605-29809-113x2ws.sh`
`==> apprenda-linux: /tmp/vagrant-shell: line 3: cd: /apprenda/repo/sys/6.8.0/System/Nodes/RPM: No such file or directory`
`==> apprenda-linux: /tmp/vagrant-shell: line 4: /apprenda/apprenda-updater/bin/configure-node.sh: No such file or directory`
`==> apprenda-linux: Waiting 60 seconds for services to come online...`

**Comment by mammerman** [comment]
Looks like this issue is here https://github.com/apprenda/bxcr/blob/master/scripts/sh/installapprenda.sh on line 3

**Comment by austinlparker** [comment]
Yup. If you change that `6.8.0` to `7.0.0` it'll work.

**Comment by mammerman** [comment]
It did work for the install.. I ended up in a funky state multiple times where the Linux node gets stuck “Activating” after being added.. I haven’t had time to investigate further other than to reproduce it 3 times.

**Comment by austinlparker** [comment]
Interesting. If you see it again, can you send me any platform logs?

**Comment by austinlparker** [comment]
I believe this has been fixed in the latest release. It was due to a bug in ACP that has been resolved. Please open a new issue if you see it again? Attach platform logs if possible. Thanks!
